package.json, src/component/order/OrderCard.tsx, src/component/order/OrderListContainer.tsx, src/page/Admin/AdminOrder.tsx, yarn.lock
주문 조회 페이지를 구현했습니다.
일단 주문이 보여지는 것 자체에 집중하여 구현만 했습니다.
> 5m
=> 주문 조회 페이지 구현

src/page/User/Register.tsx
회원가입 코드를 리팩토링 했습니다.
필요없는 구문들을 삭제하고 state기반 코드를 ref 기반으로 수정했습니다.
필요없는 주석들을 삭제했습니다. (주석은 나중에 처리하기 위해서 todo prefix를 붙이거나, 정말 중요한 코드인데 해석하기 정말 어려운 경우에만 사용해주세요)
> 10m
로그인 리팩토링은 직접 해보시라고 일부러 남겨놨습니다.
커밋단위로 보시면 리뷰하기 편합니다.
=> REFACTOR - 회원가입 관련 코드 리팩토링

src/page/User/Login.tsx
> 로그인 페이지 useRef를 이용한 리팩토링
> 10m
>
=> Refactor login component

src/component/order/NotPaidOrderCard.tsx, src/component/order/OrderCard.tsx, src/component/order/OrderListContainer.tsx, src/component/order/PaidOrderCard.tsx, src/component/order/ServedOrderCard.tsx, src/type/index.ts
주문 상태에 따른 주문 표시 방법을 분리했습니다. (결제 전, 결제됨, 서빙됨)
각 주문들에 있는 버튼을 누르면 해당 상태로 변경됩니다.
> 10m
https://github.com/Ji-InPark/KioSchool/assets/81283634/2c623368-e2cd-4dbd-b1af-5e6f0c1cf953
=> 주문 상태에 따른 주문 표시 방법 분리

src/App.tsx, src/hook/useProducts.tsx, src/page/Admin/AdminProduct.tsx, src/page/Admin/AdminWorkspace.tsx, src/recoil/atoms.ts
어드민 상품 조회 페이지를 구현했습니다.
간단하게 접속 가능하게 하기 위해서 워크스페이스 페이지에 버튼을 추가했습니다.
css 작업, 상품 수정 및 삭제 기능 순서로 후속 작업할 예정입니다.
> 5m
=> 어드민 상품 조회 페이지 구현

src/hook/useUser.tsx, src/page/Admin/AdminHome.tsx
> 워크스페이스 추가 및 삭제 기능 구현
> 5m
> 워크스페이스 추가 및 삭제 기능 구현
=> 어드민 홈 워크스페이스 추가 및 삭제 기능 구현

src/component/common/input/AppInput.tsx, src/page/User/Login.tsx
로그인 할 때 엔터를 눌러서 로그인이 가능하게금 수정했습니다.
> 3m
enterHandler prop을 만들어서 처리했습니다.
많이 사용되는 키 값이라면 이렇게 이름을 지어서 처리하는 방법도 좋을 것 같습니다.
=> EDIT - 로그인할 때 엔터 눌러서 로그인 가능하게끔 수정

src/App.tsx, src/component/common/badge/AppBadge.tsx, src/component/common/divider/HorizontalDivider.tsx, src/component/product/ProductCard.tsx, src/hook/useAdminUser.tsx, src/hook/useWorkspace.tsx, src/page/Admin/AdminHome.tsx, src/page/User/Order.tsx, src/recoil/atoms.ts, src/type/index.ts
사용자 주문 페이지의 디자인만 구현했습니다.
후속으로 주문페이지에 들어가는 기능 단위로 구현할 예정입니다.
(주문 담기 및 확인 페이지 구현, 카테고리 단위 상품 분류, 카테고리 선택 및 해당 카테고리로 스크롤 등등) 
> 10m
http://localhost:3000/orders?workspaceId=1&tableNo=1
위와 같이 query로 원하는 워크스페이스, 테이블 번호를 지정할 수 있습니다.
=> ADD - 사용자 주문 페이지 디자인 구현

src/page/User/Register.tsx
placeholder 추가 및 변수명들을 검토하여 변경했습니다
> 5m
placeholder 추가 및 변수명들을 검토하여 변경했습니다
=> 회원가입 페이지 변수명 리팩토랑

src/App.tsx, src/component/common/input/AppInputWithLabel.tsx, src/style/fonts.tsx, src/style/globalStyles.tsx
웹 폰트를 이용하여 프리텐다드 폰트를 적용했습니다.
> 5m
=> ADD - 프리텐다드 폰트 적용

src/components/order/NotPaidOrderCard.tsx, src/components/order/PaidOrderCard.tsx, src/components/order/ServedOrderCard.tsx, src/components/product/ProductCard.tsx, src/components/product/ProductDialog.tsx, src/pages/Admin/AdminProduct.tsx, src/pages/User/Order.tsx
toLocaleString을 활용하여 돈에 쉼표를 적용했습니다.
> 3m
=> EDIT - 돈에 쉼표 적용

src/components/common/label/AppLabel.tsx, src/components/product/ProductCard.tsx, src/components/product/ProductDialog.tsx, src/pages/User/Order.tsx, src/resources/svg/CloseSvg.tsx
새로 나온 주문 페이지 디자인에 맞게끔 디자인을 수정했습니다.
https://www.figma.com/file/sYBYaVOQ4RHsbghlf6YKBs/kioschool?type=design&node-id=371-498&mode=dev
> 15m
=> EDIT - 주문 페이지 디자인 적용

src/components/common/button/AppButton.tsx, src/components/product/ProductDialog.tsx, src/hooks/useApi.tsx, src/pages/User/Order.tsx
=> HOTFIX - 레이아웃 깨짐 문제 해결 배포

src/App.tsx, src/components/common/badge/AppBadge.tsx, src/components/common/button/AppButton.tsx, src/components/common/label/AppLabel.tsx, src/components/user/product/ProductCounterBadge.tsx, src/index.css, src/pages/User/Order.tsx, src/pages/User/OrderBasket.tsx, src/resources/svg/MinusButtonSvg.tsx, src/resources/svg/PlusButtonSvg.tsx
장바구니 페이지를 추가했습니다.
recoil을 사용했기 때문에 새로고침이 일어나면 state가 모두 초기화되어 내려서 새로고침을 막았습니다.
주문 상품 개수 관련 로직을 추가했습니다.
자잘한 리팩토링도 진행했습니다.
> 10m
https://github.com/Ji-InPark/KioSchool/assets/81283634/3a7810fd-ab02-4cc6-bdcb-66a4e840bb6e
=> ADD - 장바구니 페이지 추가

src/components/common/badge/AppBadge.tsx, src/pages/User/order/Order.tsx, src/pages/User/order/OrderBasket.tsx
주문 페이지 및 app badge에 padding을 적용했습니다.
> 2m
=> EDIT - 간단한 수정 사항 적용

src/App.tsx, src/components/user/product/ProductDialog.tsx, src/hooks/useOrder.tsx, src/pages/User/order/OrderBasket.tsx, src/pages/User/order/OrderComplete.tsx, src/pages/User/order/OrderPay.tsx, src/recoils/atoms.ts
주문 완료 페이지를 추가했습니다.
단순히 페이지 추가 정도로 봐주시면 좋습니다.
주문 페이지들에 간단한 애니메이션도 추가했습니다.
> 10m
=> ADD - 주문 완료 페이지 추가 및 애니메이션 추가

src/pages/Admin/AdminAccount.tsx
사용자 계좌 정보 보여주는 코드를 고쳤습니다.
> 5m
> useEffect 하나로 합쳤고 아래 조건문을 추가하여 렌더링 횟수에 있어서 이득을 얻을 수 있었습니다.
```
if (!adminUser.accountUrl) fetchAdminUser();
```
=> HOTFIX - 사용자 계좌 정보 보여주는 기능 개선

src/hooks/useAuthentication.tsx
로그인 관련 문제 수정을 배포합니다.
테스트용이므로 제대로 해결이 안됐을 가능성이 있습니다.
> 1m
=> DEPLOY - 로그인 관련 문제 수정 배포

src/hooks/useAdminUser.tsx
새로 고침시 계좌 정보가 반영 안되는 이슈 해결
> 5m
=> FIX - 새로고침 이슈

src/components/common/select/SelectWithOptions.tsx
=> REFACTOR - SelectWithOptions 리팩토링

src/hooks/useProducts.tsx
=> REFACTOR - 상품 삭제 코드 개선

src/components/common/button/AppButton.tsx
=> EDIT - AppButton 색 변경

src/hooks/useAdminOrder.tsx, src/pages/User/order/OrderBasket.tsx, src/pages/User/order/OrderComplete.tsx, src/pages/User/order/OrderPay.tsx
- 장바구니 페이지에서 아이템들이 스크롤되어있는 버그를 수정했습니다.
- 주문 완료 후 주문 확인 페이지에서 뒤로가기를 막았습니다.
- 주문 시 입금자명이 비어있으면 주문이 안되게끔 수정했습니다.
- 실시간 주문 조회를 새로 추가된 엔드포인트를 사용하게끔 수정했습니다.
> 10m
https://github.com/Ji-InPark/KioSchool/assets/81283634/a105da8a-cbad-4e8c-a975-c14947602b0c
=> EDIT - 주문 관련 디테일 잡기

src/components/common/container/Container.tsx, src/components/common/nav/NavBar.tsx, src/components/user/AuthenticationButton.tsx, src/hooks/useProducts.tsx, src/pages/Admin/AdminHome.tsx, src/pages/Admin/AdminProduct.tsx, src/pages/User/Home.tsx, src/resources/svg/ArrowRight.tsx
=> 홈페이지 디자인 적용

package.json, public/index.html, src/App.tsx, src/RouterChangeTracker.tsx, src/index.tsx, yarn.lock
- GA4를 사용하기 위한 코드들입니다.
- 몇몇 코드는 배포해봐야 확인할 수 있습니다.
> 2m
=> ADD - GA4 용 코드 추가 

src/components/common/content/AddworkspaceModalContent.tsx, src/components/common/content/WorkspaceContent.tsx, src/components/common/workspace/AddWorkspace.tsx, src/pages/Admin/AdminHome.tsx, src/pages/User/Home.tsx, src/resources/svg/ArrowRightSvg.tsx, src/resources/svg/DeleteButton.tsx, src/resources/svg/DeleteButtonSvg.tsx
워크스페이스 홈 페이지 변경된 디자인 부분을 적용했습니다.
1. 주점 사용자의 이름 표시 추가
2. 워크스페이스 삭제 svg 추가 및 호버시 효과 추가
3. 삭제 모달 input창 label을 "워크스페이스" 에서 "주점"으로 변경
> 5m
=> EDIT - 워크스페이스 홈 페이지 디자인 변경 부분 적용

src/components/admin/product/ProductCard.tsx, src/components/common/button/AppButton.tsx, src/components/common/button/SwitchButton.tsx, src/components/common/container/Container.tsx, src/components/common/modal/LoadingModal.tsx, src/components/common/nav/NavBar.tsx, src/components/common/nav/TitleNavBar.tsx, src/hooks/useProducts.tsx, src/pages/Admin/AdminProduct.tsx, src/pages/User/order/Order.tsx, src/recoils/atoms.ts, src/resources/svg/ArrowLeftSvg.tsx, src/types/index.ts, src/types/productTypes.ts
- 상품 조회 페이지 디자인을 적용했습니다.
- title nav bar, 토글 버튼을 추가하여 공통적으로 사용할 수 있게했습니다.
- admin용 product card를 추가했습니다.
- 상품 조회 페이지를 구현하면서 생긴 자잘한 수정을 진행했습니다.
> 15m
https://github.com/KioSchool/KioSchool/assets/81283634/e517a6c5-f346-4ab9-92ab-4ac08a730399
=> EDIT - 상품 조회 페이지 디자인 적용

src/pages/User/Home.tsx
- 홈 화면  애니메이션을 개선했습니다.
- 함수 내부에서 styled componenet를 선언하던게 가장 큰 문제였습니다.
> 1m
https://github.com/KioSchool/KioSchool/assets/81283634/134e457e-3d94-4015-b2f8-251917b7ba03
=> EDIT - 홈 화면 애니메이션 개선

src/App.tsx, src/components/common/container/AppContainer.tsx, src/components/common/content/MyInfoContent.tsx, src/components/common/nav/TitleNavBar.tsx, src/hooks/useApi.tsx, src/pages/Admin/AdminAccount.tsx, src/pages/User/MyInfo.tsx, src/pages/User/Register.tsx
- 계좌 관리 페이지의 디자인을 일부 적용했습니다.
- 디테일한 디자인은 논의 후 적용예정입니다.
> 3m
=> EDIT - 계좌 관리 페이지 디자인 일부 적용

src/App.tsx, src/components/common/container/AppContainer.tsx, src/components/common/nav/TitleNavBar.tsx, src/components/common/select/SelectWithLabelProps.tsx, src/components/common/select/SelectWithOptions.tsx, src/pages/Admin/AdminProduct.tsx, src/pages/Admin/AdminProductAdd.tsx
- 상품 추가 페이지에 디자인을 적용했습니다.
- 적용하면서 title nav bar에 뒤로가기 이슈가 있어, 이를 처리하기 위한 파라매터를 추가했습니다.
> 10m
=> EDIT - 상품 추가 페이지 디자인 적용

src/components/admin/product/ProductImageInput.tsx, src/components/common/select/SelectWithLabel.tsx, src/components/common/select/SelectWithLabelProps.tsx, src/pages/Admin/AdminProductAdd.tsx, src/pages/Admin/AdminProductEdit.tsx
- 상품 수정 페이지에 디자인을 적용했습니다.
- 공통적으로 사용하는 부분을 컴포넌트로 추출했습니다.
- 이전에 컴포넌트 수정하면서 select에서 값을 받아오지 못하는 문제를 해결했습니다.
> 5m
=> EDIT - 상품 수정 페이지 디자인 적용

src/components/admin/my-info/MyInfoContent.tsx, src/hooks/admin/useAdminUser.tsx
- 유저 탈퇴 기능을 연결했습니다.
- 다만 비밀번호 변경 부분이 My Info 페이지에 있는 것이 이상하다고 생각해 삭제했습니다.
> 5m
=> EDIT - My Info 페이지에 기능 연결 및 비밀번호 변경 부분 삭제

src/hooks/admin/useAdminProducts.tsx, src/pages/Admin/AdminProductEdit.tsx
- 상품 수정 페이지에 상품 삭제 버튼을 추가했습니다.
> 5m
=> ADD - 상품 수정 페이지에 상품 삭제 버튼 추가

package.json, src/App.tsx, src/components/common/content/DragAndDropContent.tsx, src/components/common/input/AppInput.tsx, src/components/common/input/AppInputWithButton.tsx, src/components/common/nav/TitleNavBar.tsx, src/hooks/admin/useAdminProducts.tsx, src/pages/Admin/AdminProductCategoires.tsx, src/resources/svg/DeleteButtonGraySvg.tsx, src/resources/svg/DragIconSvg.tsx, yarn.lock
- 카테고리 Drag and Drop 디자인 적용입니다
- react-beautiful-dnd 라이브러리를 이용하여 드래그 앤 드랍을 구현했습니다
- 드래그 아이콘, 삭제 아이콘 svg를 추가했습니다
> 5m
=> APPLY - 카테고리 Drag and Drop 디자인 적용

src/components/common/badge/AppBadge.tsx, src/components/user/order/CategoryBadgesContainer.tsx, src/components/user/order/OrderStatusBar.tsx, src/hooks/admin/useAdminProducts.tsx, src/pages/User/order/Order.tsx, src/pages/User/order/OrderComplete.tsx, src/pages/User/order/OrderPay.tsx, src/types/index.ts, src/types/productTypes.ts
- 주문 결제 페이지, 주문 내역 페이지에 디자인을 적용했습니다.
- 주문 결제 페이지에 몇가지 설명도 추가했습니다.
- 주문 페이지에서 카테고리 순서가 제대로 적용되지 않는 문제도 해결했습니다.
> 5m
=> EDIT - 주문 결제 페이지, 주문 내역 페이지 디자인 적용

src/components/common/input/AppImageInput.tsx, src/pages/Admin/AdminAccount.tsx, src/pages/Admin/AdminProductAdd.tsx, src/pages/Admin/AdminProductEdit.tsx
=> EDIT - 계좌 등록 새로운 디자인 적용

src/components/admin/order/NotPaidOrderCard.tsx, src/components/admin/order/PaidOrderCard.tsx, src/components/admin/order/ServedOrderCard.tsx, src/components/common/divider/VerticalDivider.tsx, src/components/common/input/AppCheckBox.tsx, src/hooks/admin/useAdminOrder.tsx, src/pages/Admin/order/AdminOrder.tsx
- 실시간 주문 페이지에 디자인을 적용했습니다.
- 또한 상품별 개수도 확인 가능하게 기능을 추가했습니다.
- 각 컬럼 별로 스크롤이 가능하며, 체크 박스를 통해서 각 상품별로 서빙 여부를 저장할 수 있습니다.
> 5m
=> EDIT - 실시간 주문 페이지 디자인 적용

src/App.tsx, src/hooks/useAuthentication.tsx, src/pages/User/Login.tsx, src/pages/User/ResetPassword.tsx
=> ADD - 비밀번호 재설정 페이지 추가

src/components/admin/order/PaidOrderCard.tsx, src/components/admin/order/ServedOrderCard.tsx, src/components/admin/order/ToggleOrderCard.tsx, src/pages/Admin/order/AdminOrder.tsx, src/pages/Admin/order/AdminOrderHistory.tsx, src/pages/User/order/OrderComplete.tsx, src/resources/svg/ArrowUpSvg.tsx
- 전체 주문 조회, 비밀번호 재설정 페이지 배포합니다.
> 1m
=> DEPLOY - 전체 주문 조회, 비밀번호 재설정 페이지 배포

src/hooks/admin/useAdminUser.tsx, src/pages/Admin/order/AdminOrderHistory.tsx
- 전체 주문 조회 진입시 페이지가 안보이는 버그를 수정했습니다
- dateConverter 로직 수정
- navBar와 메인 컨테이너가 겹쳐서 컨테이너의 sytle 변경
> 5m
=> FIX - 전체 주문 조회 안보이는 버그 수정

src/components/user/order/OrderButton.tsx, src/pages/User/order/Order.tsx, src/pages/User/order/OrderBasket.tsx, src/pages/User/order/OrderComplete.tsx, src/pages/User/order/OrderPay.tsx
- 0원일 때도 주문 가능하게 수정했습니다.
- 또한 0원일 때는 toss 연결없이 주문 가능하게 했습니다.
> 1m
=> EDIT - 0원일 때도 주문 가능하게 수정

src/components/admin/product/ProductCard.tsx, src/pages/Admin/AdminProductAdd.tsx, src/pages/Admin/AdminProductEdit.tsx
- 상품 추가, 변경 시 상품 이름과, 설명 길이 제한을 추가했습니다
- 자잘한 수정도 같이 진행했습니다.
> 2m
=> EDIT - 상품 추가, 변경 시 상품 이름과, 설명 길이 제한 추가

src/components/common/nav/NavBar.tsx, src/components/user/AuthenticationButton.tsx, src/styles/navBarStyles.tsx
- 변경된 Navbar 디자인을 적용했습니다.
https://github.com/user-attachments/assets/88d8edb1-0093-4e21-99de-01bdc195ac09
> 5m
- Navbar 컨텐츠는 1000px로 고정시키고, 로고 크기 조절 및 기타 라벨들 스타일를 조정했습니다.
- Navbar 배경화면에 반투명 블러효과를 추가했습니다.
=> EDIT - Navbar 변경된 디자인 적용

src/App.tsx, src/pages/SuperAdmin/SuperAdminHome.tsx
슈퍼 어드민 홈 추가
> 1m
- 기존 홈에서 전체 색상 블랙으로 변경하였습니다. (버튼, 버튼 호버, 화면 그라데이션)
- 기존 홈에서 버튼명을 "SUPER ADMIN"으로 변경하였습니다.
=> ADD - super admin home 추가

src/hooks/user/useRegister.tsx, src/pages/User/Register.tsx
- Register 컴포넌트에서 Api 통신하는 부분을 별도의 useRegister 훅으로 분리하였습니다.
> 5m
=> EDIT - Register 컴포넌트 리팩토링

src/components/common/button/RoundedAppButton.tsx, src/components/common/container/AppContainer.tsx, src/components/common/nav/TitleNavBar.tsx, src/pages/Admin/AdminAccount.tsx, src/pages/Admin/AdminOrderManageTitleNavBarChildren.tsx, src/pages/Admin/AdminProduct.tsx, src/pages/Admin/AdminProductAdd.tsx, src/pages/Admin/AdminProductCategoires.tsx, src/pages/Admin/AdminProductEdit.tsx, src/pages/Admin/AdminProductTitleNavBarChildren.tsx, src/pages/Admin/AdminWorkspace.tsx, src/pages/Admin/order/AdminOrder.tsx, src/pages/Admin/order/AdminOrderHistory.tsx, src/pages/Admin/order/AdminOrderManage.tsx, src/pages/SuperAdmin/SuperAdminManage.tsx, src/pages/SuperAdmin/SuperAdminWorkspace.tsx, src/resources/svg/ArrowLeftSvg.tsx
- 새로운 TiTleNavBar 디자인을 적용했습니다.
> 5m
- TitleNavBar를 AppContainer 안의 useTitleNavBar prop으로 받습니다.
- useScroll prop을 통해 AppContainer내부 MainContainer의 height 가 100%인지, 100vh를 동적으로 결정합니다.(기본: 100vh)
=> EDIT - TitleNavBar 새로운 디자인 적용

src/components/common/nav/TitleNavBar.tsx, src/components/common/workspace/AddWorkspace.tsx, src/components/common/workspace/DummyWorkspace.tsx, src/pages/Admin/AdminHome.tsx, src/resources/svg/PlusIconSvg.tsx
https://github.com/user-attachments/assets/722d64b1-5fac-4b56-bf24-65649d84a7d9
- 더미 어레이에 대한 새로운 디자인을 적용했습니다.
> 5m
=> EDIT - 어드민 홈 페이지 새로운 디자인 적용

src/components/admin/order/ToggleOrderCard.tsx, src/components/user/order/OrderStatusBar.tsx, src/hooks/SuperAdmin/useSuperAdminUser.tsx, src/hooks/SuperAdmin/useSuperAdminWorkspace.tsx, src/hooks/admin/useAdminOrder.tsx, src/hooks/admin/useAdminProducts.tsx, src/hooks/admin/useAdminUser.tsx, src/hooks/admin/useAdminWorkspace.tsx, src/hooks/useApi.tsx, src/hooks/useAuthentication.tsx, src/hooks/user/useOrder.tsx, src/hooks/user/useProduct.tsx, src/hooks/user/useWorkspace.tsx, src/pages/Admin/order/AdminOrder.tsx, src/pages/Admin/order/AdminOrderHistory.tsx, src/pages/User/Register.tsx, src/pages/User/order/Order.tsx, src/pages/User/order/OrderBasket.tsx, src/pages/User/order/OrderComplete.tsx, src/pages/User/order/OrderPay.tsx, src/recoils/atoms.ts, src/types/index.ts
- 가독성을 위한 리팩토링을 진행했습니다.
- 아직 모든 부분을 수정한 것은 아니니 수정된 부분에 대해서만 리뷰 부탁드립니다.
> 10m
commit 단위로 리뷰해주시길 바랍니다!
=> REFACTOR - 가독성을 위한 리팩토링

src/pages/User/Register.tsx
- 회원가입 페이지에 App Container를 적용해서 nav bar를 적용했습니다.
> 2m
=> EDIT - 회원가입 페이지에 NavBar 적용

src/components/common/nav/NavBar.tsx, src/components/common/nav/TitleNavBar.tsx
Before
After
> 5m
- NavBar 및 TitleNavBar 배경화면을 새로운 디자인으로 변경했습니다.
=> EDIT - NavBar 및 TitleNavBar 배경화면 새로운 디자인 적용

src/components/admin/product/ProductCard.tsx
=> EDIT - product card 새로운 디자인 적용

src/hooks/admin/useAdminWorkspace.tsx, src/pages/Admin/AdminWorkspace.tsx, src/pages/Admin/order/AdminOrderManage.tsx, src/recoils/atoms.ts, src/types/index.ts
- 워크스페이스에 tableCount 필드가 추가되어서, 이를 적용하였습니다.
> 8m
- 적용하는 과정에서 table-count 엔드포인트가 너무 많이 불려지는 것을 우려해 debounce 로직을 적용했습니다.
- 다만 debounce가 깔끔하게 적용된 것 같지는 않아서, 좋은 의견 있으시다면 피드백 부탁드립니다.
=> ADD - 워크스페이스에 추가된 tableCount 필드를 사용하도록 수정

src/App.tsx, src/pages/Admin/AdminWorkspace.tsx, src/pages/Admin/order/AdminTableCount.tsx
- 기존 주문 페이지 관리가 제대로 된 표현을 하지 못하는 것으로 보여서 테이블 개수 관리로 rename 했습니다.
- 또한 해당 이름에 맞게끔 route도 수정해줬습니다.
> 2m
=> EDIT - 주문 페이지 관리 -> 테이블 개수 관리로 rename

src/pages/admin/AdminProductAdd.tsx
- AdminProductAdd컴포넌트 코드 라인에 공백을 추가했습니다.
> 5m
=> REFACTOR - AdminProductAdd컴포넌트 코드 라인에 공백 추가

src/components/admin/order/AdminOrderManageTitleNavBarChildren.tsx, src/components/common/button/RoundedAppButton.tsx, src/components/super-admin/email/SuperAdminEmailTitleNavBarChildren.jsx, src/components/super-admin/email/SuperAdminEmailTitleNavBarChildren.tsx, src/components/super-admin/user/SuperAdminEmailContent.tsx, src/components/super-admin/workspace/SuperAdminSearchBar.tsx, src/hooks/super-admin/useSuperAdminEmail.tsx, src/hooks/useInputConfirm.tsx, src/pages/admin/order/AdminTableCount.tsx, src/pages/super-admin/SuperAdminEmail.tsx, src/recoils/atoms.ts
https://github.com/user-attachments/assets/b53c30b1-dca6-4abb-b821-fc3332521363
> 5m
- 슈퍼 어드민 이메일 추가하기 및 삭제하기를 구현했습니다.
- 기존에는 email을 useState로 관리를 하고 있었는데, 삭제 및 추가시에 바로 반영이 안되는 이슈가 발생하여 email에 대한 값은 recoil을 통해 관리하도록 변경했습니다.
=> FEAT - 슈퍼어드민 이메일 추가 및 삭제하기 구현

src/hooks/super-admin/useSuperAdminEmail.tsx
```js
superAdminApi
.post('/email-domain', params)
.then(() => {
fetchAllEmailDomain(0, 6);
})
.catch((error) => {
if (error.response.status === 400) {
alert('중복된 이메일 도메인입니다.');
}
});
```
- 중복된 이메일 추가에 대한 경고 문구를 출력하도록 했습니다.
> 5m
=> FEAT -  중복된 이메일 도메인 추가시 에러 핸들링

src/hooks/useCustomNavigate.tsx, src/pages/admin/order/AdminOrder.tsx, src/pages/admin/order/AdminOrderTable.tsx
- 잘못된 방식으로 navigate 사용하고 있는 부분 수정하였습니다.
> 2m
수정했으면 한 번은 잘 돌아가는지 확인해보는 습관을 기릅시다..
=> FIX - 잘못된 navigate 사용하고 있는 부분 수정

package.json, src/App.tsx, src/components/admin/workspace/WorkspaceEdit.tsx, src/components/admin/workspace/WorkspaceImageInput.tsx, src/components/common/container/AppContainer.tsx, src/hooks/admin/useAdminWorkspace.tsx, src/pages/admin/AdminWorkspace.tsx, src/pages/admin/AdminWorkspaceEdit.tsx, src/pages/admin/order/AdminOrderRealtime.tsx, src/pages/admin/order/AdminOrderTable.tsx, src/recoils/atoms.ts, src/resources/svg/PlusIconSvg.tsx, src/utils/workspaceEdit.ts, yarn.lock
https://github.com/user-attachments/assets/7b987ffd-8e70-41e5-a4fd-a073f1a1867b
https://github.com/user-attachments/assets/61d16aef-5da8-4b23-8e00-32516b1140b0
https://github.com/user-attachments/assets/b30eb325-1c05-4550-8975-8f4b727f1d1a
https://github.com/user-attachments/assets/ad1c17ab-c979-4131-8adc-4ce7e0063fc1
- 이미지 업로드 기능을 구현했습니다.
- recoil-persist 라이브러리를 통해 adminWorkspaceAtom을 로컬 스토리지에 저장하여, 새로고침해도 이전 값이 유지 됩니다.
> 5m
```js
const updateWorkspaceInfoAndImage = (
workspaceId: number,
name: string,
description: string,
notice: string | undefined,
imageIds: Array<number | null>,
imageFiles: Array<File | null>,
) => {
Promise.all([updateWorkspaceInfo(workspaceId, name, description, notice), updateWorkspaceImage(workspaceId, imageIds, imageFiles)])
.then(([infoResponse]) => { …
```
=> FEAT - 워크스페이스 이미지 업로드 기능 구현

src/components/admin/workspace/OrderRouteButtons.tsx, src/components/admin/workspace/ProductRouteButtons.tsx, src/components/admin/workspace/WorkspaceRouteButtons.tsx
=> EDIT - 주점 관리 페이지 폰트 조절 및 오타 수정

src/components/admin/order/NotPaidOrderCard.tsx, src/components/admin/order/PaidOrderCard.tsx, src/hooks/useDelayTime.tsx
- 주문이 들어온지 몇분 지났는지 계산하는 로직을 hook으로 분리했습니다.
> 2m
hook 이름 괜찮나요??
=> REFACTOR - 실시간 주문에서 사용하는 n분 전 주문 구하는 로직 hook으로 분리

.github/workflows/check_pr.yml
- pr title이 '(EDIT|FIX|ADD|REFACTOR|REMOVE|DEPLOY|REVERT) - .+' 형식으로 적혀있는지 확인하는 ci를 추가했습니다.
> 1m
=> ADD - PR title이 컨벤션대로 적혀있는지 확인하는 ci 추가

src/hooks/useApi.tsx
- 백엔드 클라우드를 옮기면서, 변경된 api 엔드포인트를 수정했습니다.
> 1m
이 pr 머지되면 바로 deploy pr 올리겠습니다.
=> EDIT - 서버 엔드포인트 수정

.github/workflows/check_pr.yml
- ci 캐싱 로직을 수정했습니다.
> 1m
이 pr에서 제대로 동작하는지 테스트하고 리뷰어 어싸인 하겠습니다.
=> EDIT - CI 캐싱 로직 수정

.github/workflows/check_pr.yml, src/hooks/useApi.tsx, src/hooks/user/useOrdersWebsocket.tsx
- 웹소켓 엔드포인트 변경한 것을 배포합니다.
> 1m
=> DEPLOY - 웹소켓 엔드포인트 변경 배포

src/components/user/info/info-main/InfoMain.tsx, src/components/user/info/info-main/InfoMainDescription.tsx, src/pages/user/info/InfoMobile.tsx
- 반응형으로 모바일 info main 컴포넌트를 구현했습니다.
- sign in 버튼은 모바일에 있어도 의미가 없다고 판단해 노출이 안되게끔 했습니다.
> 5m
=> ADD - 모바일 InfoMain 컴포넌트 구현

src/components/user/info/InfoTitle.tsx, src/components/user/info/info-benefit/InfoBenefit.tsx, src/components/user/info/info-benefit/InfoBenefitFeatureList.tsx, src/components/user/info/info-benefit/InfoBenefitImage.tsx, src/pages/user/info/InfoMobile.tsx
- 반응형으로 InfoBenefit 컴포넌트를 구현했습니다.
> 5m
=> ADD - 모바일 InfoBenefit 컴포넌트 구현

src/components/user/info/info-statistic-and-review/InfoStatisticAndReview.tsx, src/pages/user/info/InfoMobile.tsx, src/resources/svg/AnimatedInfoLineGraphSvg.tsx
- 반응형으로 InfoStatisticsAndReview 컴포넌트를 구현했습니다.
> 5m
=> ADD - 모바일 InfoStatisticsAndReview 컴포넌트 구현

src/components/user/info/info-our-service/InfoOurService.tsx, src/pages/user/info/InfoMobile.tsx
- 반응형으로 InfoOurServices 컴포넌트를 구현했습니다.
- 아직 디자인이 완료되지 않아서 나머지 부분은 맨마지막에 구현하겠습니다.
> 5m
=> ADD - 모바일 InfoOurServices 컴포넌트 구현

src/components/admin/order/OrderStickyNavBar.tsx
- OrderStickyNavBar가 공통적으로 사용되게끔 수정했습니다.
> 5m
기존 OrderStickyNavBar에 props를 추가했습니다. 기존 order에서는 코드 변경없이도 제대로 돌아갑니다.
=> EDIT - OrderStickyNavBar 공통부분 처리를 위한 수정

src/pages/user/order/OrderPay.tsx
- 결제 진행 페이지에 새로운 디자인을 적용했습니다.
- 이 후 디자인에 따라 새로운 기능이 들어갈 수도 있긴 한데 일단 현재 디자인만 구현했습니다.
> 5m
=> EDIT - 결제 진행 페이지 새로운 디자인 적용

src/components/common/divider/HorizontalDivider.tsx, src/components/user/order/OrderFooter.tsx, src/components/user/order/WorkspaceNotice.tsx, src/components/user/product/ProductCard.tsx, src/pages/user/order/Order.tsx, src/resources/svg/MinusIconSvg.tsx
https://github.com/user-attachments/assets/dd754979-fc46-4363-b834-8c346215b307
- Order 컴포넌트 내에서 MainContent에 대한 디자인을 적용했습니다.
> 5m
=> ADD - Order 페이지 컨텐츠 디자인 구현

src/components/admin/order/OrderStickyNavBar.tsx, src/components/user/product/ProductCard.tsx, src/components/user/product/ProductCounterBadge.tsx, src/pages/user/order/OrderBasket.tsx
https://github.com/user-attachments/assets/5cbd229c-ceb3-450e-8f2d-a787dd6adf09
- 장바구니 페이지에 대한 새로운 디자인을 구현했습니다.
- 상품 삭제 및 전체 삭제 핸들러를 추가했습니다.
> 5m
=> ADD - 장바구니 페이지 새로운 디자인 구현

src/components/user/info/info-our-service/InfoOurService.tsx, src/components/user/info/info-our-service/InfoServiceCard.tsx
- 모바일 랜딩페이지 our service 디자인을 적용했습니다.
> 5m
=> EDIT - 모바일 랜딩페이지 our service 디자인 적용

src/components/user/order/OrderFooter.tsx, src/pages/user/order/Order.tsx, src/pages/user/order/OrderProductContent.tsx
- Order 페이지 placeholder 추가했습니다.
- 상품 부분들을 OrderProductContent라는 별도의 컴포넌트로 분리했습니다.
> 5m
=> EDIT - Order 페이지 placeholder 추가

src/components/user/info/info-creators-word/InfoCreatorsContent.tsx, src/components/user/info/info-creators-word/InfoCreatorsContentMobile.tsx, src/components/user/info/info-main/InfoMainDescription.tsx, src/components/user/info/info-our-service/InfoOurService.tsx, src/components/user/info/info-our-service/InfoServiceCard.tsx, src/components/user/info/info-statistic-and-review/InfoStatisticAndReview.tsx
- 랜딩페이지에 work-break를 추가해서 가독성을 높였습니다.
> 5m
=> ADD - 랜딩페이지에 word-break 추가하기

src/App.tsx, src/components/common/pagination/PaginationSearchBar.tsx, src/components/common/pagination/PaginationSearchContents.tsx, src/components/super-admin/bank/SuperAdminBankContent.tsx, src/components/super-admin/bank/SuperAdminBankTitleNavBarChildren.tsx, src/components/super-admin/email/SuperAdminEmailDomainContent.tsx, src/hooks/super-admin/useSuperAdminBank.tsx, src/pages/super-admin/SuperAdminBank.tsx, src/pages/super-admin/SuperAdminEmailDomainList.tsx, src/pages/super-admin/SuperAdminManage.tsx, src/pages/super-admin/SuperAdminUser.tsx, src/pages/super-admin/SuperAdminWorkspace.tsx, src/pages/user/UserEmailDomain.tsx, src/recoils/atoms.ts
- 수퍼어드민 페이지에 은행 관리 페이지를 추가했습니다.
- 또한 페이지네이션에서 사용하는 컴포넌트를 super admin이 아닌 pagination으로 rename했습니다.
> 5m
=> ADD - super admin 은행 관리 페이지 추가

src/components/user/info/info-footer/InfoFooter.tsx
- info 페이지에 notion 배지를 추가하여 faq를 볼 수 있도록 처리했습니다.
> 5m
- pc 화면
- 모바일 화면
=> ADD - Info 페이지에 notion badge 추가

src/pages/user/order/OrderPay.tsx
- 결제창에서 토스가 사용 가능한 상태라면 토스 결제창이 먼저 선택되게끔 수정했습니다.
> 3m
=> EDIT - 결제창에서 토스가 사용 가능한 상태라면 토스 결제창이 먼저 선택되게끔 수정

src/components/common/input/AppInputWithLabel.tsx, src/pages/user/Register.tsx, src/pages/user/order/OrderPay.tsx
- 회원가입 페이지에 회원 가입 가능한 이메일 도매인 링크 추가 배포합니다.
> 1m
=> DEPLOY - 회원가입 페이지에 회원 가입 가능한 이메일 도매인 링크 추가 배포

src/components/common/container/AppContainer.tsx
- 사파리 대응을 위한 AppContainer css 수정했습니다.
> 1m
=> FIX - 사파리 대응을 위한 AppContainer css 수정

src/pages/admin/AdminAccount.tsx, src/pages/admin/AdminMyInfo.tsx
- AppContainer의 title nav bar 사용하게끔 수정했습니다
- 또한 뒤로가기 버튼이 잘못동작하고 있는 것을 수정했습니다.
> 1m
=> REFACTOR - AppContainer의 title nav bar 사용하게끔 수정

src/pages/user/order/OrderPay.tsx
- 품절 상품이 포함된 주문 생성시 주문 화면으로 돌아가는 기능을 추가했습니다.
- 돌아가기전에 장바구니를 모두 비우게끔 했습니다.
- 저는 이 구현이 괜찮아보였는데 더 좋은 방법이 있다면 의견 부탁드립니다!
> 5m
https://github.com/user-attachments/assets/f7542d38-ab31-4d11-965b-68537abaf144
=> ADD - 품절 상품이 포함된 주문 생성시 주문 화면으로 돌아가는 기능 추가

public/index.html, src/components/common/button/NewRoundedButton.tsx, src/components/common/input/NewAppInput.tsx, src/pages/admin/AdminAccount.tsx, src/styles/flexStyles.tsx
- 새로운 디자인을 적용한 컴포넌트들을 구현했습니다.
- New 접두사를 붙여서 기존 컴포넌트와 구분되게 했습니다.
- 핵심이 되는 2가지 컴포넌트 (RoundedButton, AppInput)만 적용했고, 의존 관계에 있는 컴포넌트들도 교체할 예정입니다.
- 위 사진은 임시로 적용한 모습이고 PR 커밋에는 올라와있지 않습니다.(어떤 느낌인지 보여주는 용도)
> 5m
```ts
export type JustifyType = 'start' | 'end' | 'center' | 'space-between' | 'space-around' | 'space-evenly' | 'flex-start' | 'flex-end';
export type AlignItemsType = 'stretch' | 'start' | 'end' | 'center' | 'baseline' | 'flex-start' | 'flex-end';
interface FlexProps {
justify?: JustifyType;
align?: AlignItemsType;
}
```
- flexStyles애 type을 추가하여 justify 및 align의 값을 제한하였습니다.(+ 인텔리센스 가능)
=> ADD - 새로운 Button 및 Input 디자인 적용

.github/workflows/check_pr.yml, .github/workflows/create_cache.yml, package.json, yarn.lock
=> EDIT - node 버전 22로 업그레이드

src/components/user/order/OrderAccountInfo.tsx
- 사파리 환경에서 계좌 복사하기 버튼이 깨지는 현상을 스타일을 강제하여 수정했습니다.
- 원인은 모릅니다...
> 1m
=> EDIT - 계좌 복사하기 버튼이 깨지는 현상 수정

src/pages/user/order/OrderPay.tsx
- 사파리에서 팝업 차단을 우회하는 기능을 추가했습니다.
- https://milooy.github.io/dev/avoid-blocking-popup-in-safari/
- https://developer.mozilla.org/en-US/docs/Web/API/Location/href
> 5m
=> EDIT - Safari에서 팝업 차단 우회하는 기능 추가

src/pages/user/order/OrderPay.tsx
- 사파리 브라우저에서 팝업 차단 시 우회하는 내용에 대한 배포입니다.
> 5m
=> DEPLOY - 사파리 브라우저 이슈 대응 내용 배포

src/components/common/container/PreviewContainer.tsx
https://github.com/user-attachments/assets/0ee4d07e-be4d-44e9-84f4-757542fb1af4
- 동적으로 QR 코드를 렌더링 한 뒤 다운로드 하는 기능을 추가했습니다.
> 5m
```ts
flushSync(() => {
root.render(<QRCodeCanvas value={previewUrl} size={200} level="H" bgColor="#FFFFFF" fgColor="#000000" />);
});
```
- `flushSync`를 사용하여 QR 코드 렌더링을 동기적으로 실행합니다.
=> ADD - 미리보기 QR 코드 다운로드 기능 추가

public/index.html, src/App.tsx, src/RouterChangeTracker.tsx
```js
// index.html
<script>
if(window.location.hostname !== 'localhost') {
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-XGYLSPGK2G');
}
</script>
// RouterChangeTracker()
function RouterChangeTracker() {
const location = useLocation();
// location 변경 감지시 pageview 이벤트 전송
if (!isDevelopment) {
ReactGA.set({ page: location.pathname });
ReactGA.send('pageview');
}
}, [location]);
}
export default RouterChangeTracker;
```
- 개발 환경일 때에는 GA에 요청을 보내지 않도록 했습니다.
> 5m
=> ADD - 개발 환경에서의 GA 요청 차단

src/components/admin/product/ProductCard.stories.tsx, src/components/admin/product/ProductCard.tsx, src/components/common/button/SwitchButton.tsx, src/pages/admin/AdminProduct.tsx
- 새로운 상품 관리 컴포넌트 및 디자인 적용했습니다.
- info component는 나중에 한 번에 적용하겠습니다.
> 10m
=> EDIT - 새로운 상품 관리 컴포넌트 및 디자인 적용

src/components/admin/order/ToggleOrderCard.tsx
- 전체 주문 조회 시 레이아웃이 콘텐츠 길이에 따라 달라지던 문제를 해결했습니다.
> 1m
before
after
=> EDIT - 전체 주문 조회 시 레이아웃이 콘텐츠 길이에 따라 달라지던 문제 해결

package.json, src/pages/admin/order/AdminOrderHistory.tsx, yarn.lock
- 전체 주문 조회 기간에 시간도 설정 가능하게끔 추가했습니다.
> 5m
=> ADD - 전체 주문 조회 기간에 시간도 설정 가능하게끔 추가

.eslintrc, package-lock.json, src/components/admin/workspace/WorkspaceContent.stories.tsx, src/components/admin/workspace/WorkspaceContent.tsx, src/components/common/workspace/AddWorkspace.stories.tsx, src/components/common/workspace/AddWorkspace.tsx, src/components/common/workspace/modal/AddWorkspaceModalButton.tsx
- 워크스페이스 홈에 새로운 디자인을 적용했습니다.
> 5m
=> EDIT - 워크스페이스 홈 새로운 디자인 적용

src/components/common/input/NewAppInput.tsx, src/components/common/label/LinkLabel.stories.tsx, src/components/common/label/LinkLabel.tsx, src/pages/user/Register.tsx
- 새로운 회원가입 디자인을 적용했습니다.
- LinkLabel 컴포넌트 및 스토리를 추가했습니다.
> 5m
```ts
interface InputButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
size?: CustomButtonSize;
text: string;
}
interface NewAppInputProps extends React.InputHTMLAttributes<HTMLInputElement> {
// 기타 props...
buttonProps?: InputButtonProps;
}
<NewRoundedButton
{...props.buttonProps} // 버튼 엘리먼트에 props 넘겨줌
size={'xs'}
customSize={props.buttonProps.size}
onClick={props.enterHandler}
style={{ marginLeft: 'auto', marginRight: '10px' }}
>
{props.buttonProps.text}
</NewRoundedButton>
```
- 기본 버튼 타입을 확장한 InputButtonProps 인터페이스를 선언하여 props로 onClick, disabled와 같은 기본 버튼 속성을 넘겨줄 수 있도록 했습니다.
```ts
const passwordRegex = /^(?=.*[a-zA-Z])(?=.*\d)(?=.*[!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?])[a-zA-Z\d!@#$%^&*()_+\-=\[\]{};':"\\|,.<> …
```
=> EDIT - 회원가입 새로운 디자인 적용

src/pages/user/Login.tsx, src/pages/user/Register.tsx, src/pages/user/ResetPassword.tsx
- 로그인 및 비밀번호 찾기에 새로운 디자인을 적용했습니다.
> 5m
```ts
const [userPasswordInput, setUserPasswordInput] = useState<string>('');
const [checkUserPasswordInput, setCheckUserPasswordInput] = useState<string>('');
if (userPasswordInput || checkUserPasswordInput) {
validatePassword();
} else {
setErrorMessage('');
}
}, [userPasswordInput, checkUserPasswordInput]);
<NewAppInput
label={'비밀번호'}
placeholder={'비밀번호를 입력해주세요'}
type={'password'}
onChange={() => {
setCheckUserPasswordInput('');
}}
ref={userPasswordInputRef}
required
/>
<NewAppInput
label={'비밀번호 확인'}
placeholder={'입력한 비밀번호를 똑같이 입력해주세요'}
type={'password'}
value={checkUserPasswordInput}
onChange={(event: React.ChangeEvent<HTMLInputElement>) => {
setCheckUserPasswordInput(event.target.value);
validatePassword(event.target.value);
}} …
```
=> EDIT - 새로운 로그인 및 비밀번호 찾기 디자인 적용

src/components/admin/product-category/CategoryDraggableContents.tsx, src/pages/admin/AdminProductCategoires.tsx
- 카테고리 페이지에 새로운 디자인을 적용했습니다.
> 5m
=> EDIT - 카티고리 페이지 새로운 디자인 적용

src/components/common/input/AppImageInput.tsx
```ts
/**
* “사진 업로드” 기능을 수행합니다.
*
* 버튼 클릭 시 숨겨진 파일 입력(<ImageInput />)을 프로그래밍적으로 클릭하여
* 이미지 선택 다이얼로그를 열고, 이미지 파일만 선택 가능하며 선택 시 onImageChange가 호출됩니다.
*/
const uploadImage = () => {
document.getElementById('img')?.click();
};
```
- [이전 PR](https://github.com/KioSchool/KioSchool/pull/259)에서 미반영된 리뷰를 반영했습니다.
- 사진 업로드 익명 함수를 `uploadImage`함수로 선언하고, JSDoc 기능을 통해 역할을 명시했습니다.
> 5m
=> FIX - 미반영 리뷰 반영

src/components/common/button/AppFaqButton.tsx, src/pages/admin/AdminWorkspace.tsx
=> ADD - FAQ 버튼 추가 및 적용

src/hooks/admin/useAdminOrder.tsx, src/pages/admin/order/AdminOrderHistory.tsx
- 전체 주문 조회 시 프론트에서 filtering 하던 부분을 백엔드로 책임을 위임했습니다.
> 5m
=> EDIT - 전체 주문 조회 fetch 로직 변경

src/components/admin/order/OrderStickyNavBar.tsx, src/components/user/product/ProductCounterBadge.tsx, src/pages/user/order/OrderBasket.tsx, src/pages/user/order/OrderPay.tsx
- 디자인에 따라 사용자 주문 화면 디자인을 수정했습니다.
> 5m
=> EDIT - 사용자 주문 화면 디자인 수정

src/components/admin/order/ToggleOrderCard.tsx, src/pages/admin/order/AdminOrderTableHistory.tsx
-  테이블별 주문 조회 전체 주문 조회와 똑같은 디자인으로 변경했습니다.
> 5m
=> EDIT - 테이블별 주문 조회 전체 주문 조회와 똑같은 디자인으로 변경

public/index.html
- 브라우저 자동 번역 기능 사용하지 않도록 수정했습니다.
- 또한 우리 웹의 기본 언어를 한국어로 수정했습니다.
> 1m
https://velog.io/@nijuy/classnotranslate%EC%9C%BC%EB%A1%9C-%EB%B8%8C%EB%9D%BC%EC%9A%B0%EC%A0%80-%EB%B2%88%EC%97%AD-%EA%B8%B0%EB%8A%A5-%EB%81%84%EA%B8%B0
=> EDIT - 브라우저 자동 번역 기능 사용하지 않도록 수정

.storybook/preview.ts, src/components/admin/order/OrderStickyNavBar.stories.tsx, src/components/admin/order/OrderStickyNavBar.tsx
- 주점 이름이 넘치는 경우, 밑줄임을 하도록 스타일을 조정했습니다.
> 5m
=> EDIT - 주점 이름 넘칠 시 밑줄임 적용

src/App.tsx, src/components/common/fallback/ServerErrorFallback.tsx, src/hooks/useServerHealth.tsx
=> ADD - 서버 오류 Fallback UI 추가

src/pages/user/Login.tsx
- 로그인 페이지 진입 시 id input에 auto focus 추가했습니다.
> 1m
=> ADD - 로그인 페이지 진입 시 id input에 auto focus 추가

src/pages/admin/order/AdminTableCount.tsx
- 전체 QR 코드 다운로드 화질을 개선했습니다.
- 기존 사파리 브라우저에서 단일 QR 코드 다운로드가 안되는 이슈를 해결했습니다.
> 5m
=> EDIT - 전체 QR 코드 다운로드 화질 개선

src/pages/user/order/OrderComplete.tsx
- 빌드 실패를 해결했습니다.
> 5m
- null에 대한 예외처리 조건문을 추가해줬습니다.
```ts
return () => {
if (intervalId) {
clearInterval(intervalId);
}
};
```
=> FIX - 빌드 실패 수정

src/hooks/user/useOrdersWebsocket.tsx
- StompJS Client 는 webSocketFactory을 통해 StockJS기반으로 작동하게 됩니다. 따라서 더이상 brokerURL이 의미가 없습니다.
- brokerURL이 없어도 잘 작동하는 모습
https://github.com/user-attachments/assets/5e61be74-b53b-412b-b15c-44afa818b71e
> 5m
=> FIX - 쓸모없는 brokerURL 제거
