- src/hook/useCustomNavigate.tsx
- src/page/Admin/AdminWorkspace.tsx
워크스페이스 페이지에서 주문 조회 페이지로 연결하는 버튼 추가했습니다.
현재 location에서 path만 붙여주면 되는 부분인데 다른 곳에서도 사용할 것 같아서 hook으로 만들었습니다.
> 3m
> 워크스페이스 페이지에서 주문 조회 페이지로 연결하는 버튼 추가

- src/hook/useUser.tsx
- src/page/Admin/AdminHome.tsx
- src/recoil/atoms.ts
어드민 홈페이지에서 접근가능한 워크스페이스 보여주게 구현했습니다.
또한 해당 워크스페이스 페이지로 넘어갈 수 있게 버튼도 붙여놨습니다.
이 후에 해당 워크스페이스에 상품을 조회하고 추가 및 수정할 수 있는 페이지를 구현할 예정입니다.
> 3m
> 어드민 홈페이지에서 접근가능한 워크스페이스 보여주기

- src/component/common/button/AppButton.tsx
- src/component/product/ProductCard.tsx
- src/component/product/ProductDialog.tsx
- src/page/User/Order.tsx
- src/recoil/atoms.ts
- src/resource/svg/CloseSvg.tsx
- src/type/index.ts
주문 페이지에서 상품을 선택하면 상품을 선택하여 장바구니에 추가할 수 있게 추가했습니다.
또한 해당 상품들의 총합을 구하여 주문 버튼도 보여주게 수정했습니다.
> 15m
ProductDialog가 추가되었습니다.
또한 주문 버튼은 총합이 0원보다 많아야지 노출됩니다.
> ADD - 주문페이지에 모달창 추가 및 주문 버튼 생성

- src/hooks/useAdminUser.tsx
- src/pages/Admin/AdminAccount.tsx
- src/pages/Admin/AdminHome.tsx
- src/recoils/atoms.ts
> 사용자의 등록된 계좌 정보를 보여줍니다.
> 5m
> 
계좌 정보를 useReducer를 통해 상태 관리합니다. 
사용자의 정보를 담는 adminUserAtom을 만들었습니다.
recoil을 통해 사용자 계좌정보를 가져오기 때문에 새로고침을 하게 되면 계좌정보가 NULL로 초기화 되는 문제가 있습니다.
> 사용자의 계좌 정보 보여주는 기능

- src/pages/User/order/OrderPay.tsx
ux를 생각해봤을 때 계좌 정보를 복사하는 과정이 오히려 헷갈릴 가능성이 높다고 생각해서 계좌 정보를 볼 수 없게 삭제했습니다.
(계좌 정보 복사 버튼을 누르자마자 주문이 들어가야하는데 헷갈려서 여러번 누르면 주문이 여러번 들어간다던가 하는 문제가 생길 수 있음)
> 1m
> REMOVE - 결제 주문 페이지에서 계좌 정보 삭제

- src/components/common/content/WorkspaceContent.tsx
- src/hooks/useConfirm.tsx
- src/recoils/atoms.ts
- custom confirm hook을 추가했습니다.
- 워크스페이스 탈퇴시 사용하던 내장 confirm 대신 custom hook을 사용하게끔 수정했습니다.
> 5m
> EDIT - custom confirm hook 추가 및 워크스페이스 탈퇴 시 적용

- src/components/user/AuthenticationButton.tsx
- src/hooks/useApi.tsx
- src/hooks/useAuthentication.tsx
- 로그인 쿠키가 만료되었지만 로그아웃 처리가 되지 않아서 로그인 된 것 처럼 보이는 문제가 있었다.
- 이를 해결하려고 보니 logout에서 navigate까지 처리하고 있어서 login page로 이동하는 것이 아닌 home으로 이동하고 있었다. 
- navigate의 책임을 logout이 아닌 logout을 사용하는 곳으로 넘기기 위해서 logout에서 Promise를 반환하게 수정했다.
- 또한 쿠키가 만료되었을 때 isLoggedIn 쿠키도 초기화 시켜주었다.
> 3m
> FIX - 로그인 쿠키 관련 에러 처리

- src/components/SuperAdmin/workspace/SuperAdminWorkspaceContent.tsx
https://github.com/user-attachments/assets/9b255a07-b70f-4679-8076-0529c19293b2
- 워크스페이스 라벨을 클릭시 새로운 탭으로 해당 워크스페이스 페이지를 엽니다.
> 5m
- useNavigate 대신에 window.open( ) 함수를 사용했습니다.
> FEAT - 슈퍼어드민 워크스페이스에서 워크스페이스 클릭 시 새로운 탭으로 열리는 기능 추가

- src/App.tsx
- src/components/common/button/ImageRouteButton.tsx
- src/pages/Admin/AdminWorkspace.tsx
- src/pages/SuperAdmin/SuperAdminHome.tsx
- src/pages/SuperAdmin/SuperAdminManage.tsx
https://github.com/user-attachments/assets/d0e459d0-498c-4984-a46f-abd2e0b7bdd0
- 슈퍼어드민 home에서 manage 페이지로 이동할 수 있는 링크 추가했습니다.
- 슈퍼어드민 manage 페이지의 전체적인 프레임을 구성했습니다.
> 5m
- ImageRouteButton 및 해당 컨테이너에 대해 추후 공용 컴포넌트에 추가할 예정입니다.
- titleNavBar에 대한 새로운 디자인을 추가 적용할 예정입니다.
> FEAT - 슈퍼어드민 manage 페이지 구현

- src/hooks/useApi.tsx
https://github.com/user-attachments/assets/73aa6d93-cfd4-45c9-83d1-a1ab1eb23fa5
https://github.com/user-attachments/assets/b1f07e53-163b-447b-ac5a-737c1d10d753
setTimeOut( ) 함수를 이용해, 500ms 이상 걸리는 요청에만 로딩창을 보여주도록 했습니다.
> 5m
> FEAT - 서버 요청 시 짧은 Response에 대해 로딩창 보여주지 않기

- src/components/SuperAdmin/user/SuperAdminUserContent.tsx
- src/components/SuperAdmin/workspace/SuperAdminWorkspaceContent.tsx
- src/components/admin/order/NotPaidOrderCard.tsx
- src/components/admin/order/PaidOrderCard.tsx
- src/components/admin/order/ServedOrderCard.tsx
- src/components/admin/product-category/CategoryDraggableContents.tsx
- src/components/admin/workspace/WorkspaceContent.tsx
- src/components/common/badge/AppBadge.tsx
- src/components/common/button/AppButton.tsx
- src/components/common/button/ImageRouteButton.tsx
- src/components/common/button/RoundedAppButton.tsx
- src/components/common/button/SwitchButton.tsx
- src/components/common/container/AppContainer.tsx
- src/components/common/input/AppImageInput.tsx
- src/components/common/input/AppInputWithButton.tsx
- src/components/common/label/AppLabel.tsx
- src/components/common/workspace/modal/CreateWorkspaceModal.tsx
- src/components/user/order/OrderButton.tsx
- src/components/user/product/ProductDialog.tsx
- src/hooks/useConfirm.tsx
- src/pages/Admin/order/AdminOrder.tsx
- src/pages/Admin/order/AdminOrderManage.tsx
- src/pages/User/Home.tsx
- src/pages/User/Info.tsx
- src/pages/User/order/Order.tsx
- src/pages/User/order/OrderBasket.tsx
- src/pages/User/order/OrderComplete.tsx
- src/pages/User/order/OrderPay.tsx
- src/resources/colors.tsx
- src/styles/navBarStyles.tsx
`export const enum Color {
'grey' = '#5c5c5c',
'white' = 'white',
'black' = 'black',
'kioOrange' = '#EB6D09'
}
`
> 5m
- 색상에 대하여 const enum을 적용했습니다.
- AppLabel에 color prop을 추가하여 confirm 창의 color를 흰색으로 적용했습니다.
> FEAT - 색상 관련 const enum 적용

- src/components/common/nav/TitleNavBar.tsx
https://github.com/user-attachments/assets/14ef1180-26ed-408a-b56a-e77a1ca12654
https://github.com/user-attachments/assets/35675d13-a495-4092-8564-7d40abf4b4af
- TitleNavBar의 height값을 50px로 고정하여 통일성 있는 디자인을 구현하였습니다.
> 5m
> EDIT - TitleNavBar의 height 값을 50px로 고정

- package.json
- src/pages/admin/order/AdminTableCount.tsx
- yarn.lock
- AdminTableCount에서 QRCodeCanvas DOM 접근 방식을 useRef로 변경하려 시도했습니다.
> 5m
```js
const canvas = document.getElementById(`qrcode-${tableNo}`) as HTMLCanvasElement;
```
```js
const QRCodeCardRefs = useRef<{ [key: number]: HTMLDivElement | null }>({});
// . . . . .
const qrDiv = QRCodeCardRefs.current[tableNo];
const canvas = qrDiv.querySelector('canvas') as HTMLCanvasElement;
// . . . . .
<div ref={(el) => (QRCodeCardRefs.current[index] = el)}>
<QRCodeCanvas value={`${baseUrl}/order?workspaceId=${workspaceId}&tableNo=${index + 1}`} size={150} />
</div>
```
원래는 다음과 같이 QRCodeCanvas에 직접적으로 ref를 넘겨주려 했는데 QRCodeCanvas에서 ref를 prop으로 받을 수 없게 선언되어 있었습니다.
```js
<QRCodeCanvas . . . ref={(el) => (QRCodeCardRefs.current[index] = el)} />
```
이와 관련하여 찾아보니 [can't get the …
> REFACTOR - AdminTableCount에서 QRCodeCanvas DOM 접근 방식 재고

- src/components/super-admin/SuperAdminSearchContents.tsx
- src/components/super-admin/workspace/SuperAdminSearchBar.tsx
- src/hooks/admin/useAdminOrder.tsx
- src/hooks/super-admin/useSuperAdminUser.tsx
- src/hooks/super-admin/useSuperAdminWorkspace.tsx
- src/pages/admin/AdminProductAdd.tsx
- src/pages/admin/AdminProductEdit.tsx
- src/pages/admin/order/AdminOrderTableHistory.tsx
- src/pages/super-admin/SuperAdminUser.tsx
- src/pages/super-admin/SuperAdminWorkspace.tsx
- src/recoils/atoms.ts
- src/types/paginationType.ts
- Pagination 부분에서 recoil 대신 useState로 사용하려 했습니다.
> 5m
```jsx
const fetchAllUsers = (page: number, size: number, name?: string) => {
const params: FetchAllUsersParamsType = { page, size, name };
const response = superAdminApi
.get<PaginationResponse<User>>('/users', { params })
.then((res) => {
searchParams.set('page', params.page.toString());
setSearchParams(searchParams);
return res.data;
})
.catch((error) => {
console.error(error);
return null;
});
return response;
};
```
`fetchAllUsers` 함수로 위와 같은 형태로 받아온 데이터(`res.data`)를 반환하고, 
```jsx
const [users, setUsers] = useState<PaginationResponse<User> | null>(null);
const userResponse = async () => {
const response = await fetchAllUsers(0, pageSize);
setUsers(response);
};
userResponse();
}, []);
```
사용하는 곳에서 `useState`로 관리하려 …
> FEAT - Pagination 부분 recoil 대체

- src/components/admin/my-info/MyInfoContent.tsx
- src/components/admin/product-category/CategoryDraggableContents.tsx
- src/components/admin/workspace/WorkspaceContent.tsx
- src/components/common/button/AppButton.tsx
- src/hooks/useConfirm.tsx
- src/pages/admin/AdminProductEdit.tsx
```js
const ButtonContainer = styled.div`
${rowFlex({ justify: 'space-between' })}
gap: 12px;
`;
. . .
interface ConfirmProps {
title: string;
description: string;
okText: string;
cancelText?: string;
}
```
> 5m
- flexStyle 적용 및 ConfirmProps를 통해 인자를 넘겨주는 방식을 변경했습니다.
> REFACTOR - useConfirm hook 리팩토링

- src/components/super-admin/workspace/SuperAdminSearchBar.tsx
- src/hooks/admin/useAdminOrder.tsx
- src/hooks/super-admin/useSuperAdminEmail.tsx
- src/hooks/super-admin/useSuperAdminUser.tsx
- src/hooks/super-admin/useSuperAdminWorkspace.tsx
- src/hooks/useCustomNavigate.tsx
- src/hooks/user/useEmail.tsx
- src/pages/admin/order/AdminOrderTableHistory.tsx
- src/pages/super-admin/SuperAdminEmailDomainList.tsx
- src/pages/super-admin/SuperAdminManage.tsx
- src/pages/super-admin/SuperAdminUser.tsx
- src/pages/super-admin/SuperAdminWorkspace.tsx
- src/pages/user/UserEmailDomain.tsx
https://github.com/user-attachments/assets/fc4f66b7-4a18-461a-9bc7-5b4ddf7fa212
> 5m
- `setSearchParams`의 `replace`옵션을 추가하여 구현했습니다.
```js
setSearchParams(searchParams, { replace });
```
- 다른 page를 이동했다가 뒤로 가기 클릭 시 이전 page 내용이 안 불러와지는 버그를 수정했습니다.
- `useEffect`에서 `searchParams`를 의존성 배열에 넣어 page가 변경될 때 마다 바뀐 page 내용을 불러옵니다.
```js
const nowPage = Number(searchParams.get('page'));
const searchValue = userInputRef.current?.value || '';
fetchAndSetWorkspaces(nowPage, pageSize, searchValue, true);
}, [searchParams]);
```
> FIX - pagination 페이지에서 뒤로 가기 클릭 시 쿼리스트링 값에 의해 2번 클릭해야 하는 버그 수정

- src/components/admin/order/NotPaidOrderCard.tsx
- src/components/admin/order/modal/OrderModalHeaderContents.tsx
- src/components/admin/order/modal/OrderModalMainContents.tsx
- src/components/common/modal/LoadingModal.tsx
https://github.com/user-attachments/assets/04540142-c659-4531-ad85-3ead0f8feeaf
- 상세 주문 모달창의 수평선에 대한 height를 디자인에 맞춰 적용했습니다.
- 상품 옆의 가격을 서빙된 상품의 개수에 맞춰 동적으로 보여줍니다.
> 5m
- 상품 합계 가격은 동적으로 보여주지 않아도 괜찮은 건지 궁금합니다!
> FIX - 실시간 주문 조회 페이지 미반영된 디자인 반

- src/pages/admin/order/AdminOrder.tsx
```js
<ImageRouteButton onClick={() => navigateWithPage('/order/table')} buttonText={'테이블별 주문 조회'} />
```
- 기존 replaceLastPath대신 navigateWithPage로 대체했습니다.
> 5m
> FIX - AdminOrderTableHistory 진입 시 navigateWithPage 사용하게 수정

- package.json
- src/pages/admin/order/AdminTableCount.tsx
- yarn.lock
- 테이블 관리 페이지에 html-to-image를 적용하여 qr코드를 다운받을 때 테이블 번호도 같이 다운받도록 수정했습니다.
> 5m
다운로드 된 사진
> EDIT - 테이블 관리 페이지에 html-to-image 적용

- src/components/admin/order/AdminOrderManageTitleNavBarChildren.tsx
- src/pages/admin/order/AdminTableCount.tsx
- 테이블 개수 관리 페이지에서 개별 다운로드 버튼을 없애고 qr code 이미지에 해당 기능을 위임했습니다.
- 또한 qr code 전체 다운로드 기능을 추가했습니다.
> 2m
전체 이미지를 가져오기 위해서 ref에서 current의 style을 직접 접근해서 고치는 부분이 있습니다.
> ADD - QR 코드 전체 다운로드 기능 추가

- src/pages/admin/AdminWorkspace.tsx
- 프리뷰 페이지와 라우터 컨테이너의 flex를 start로 조정했습니다.
> 5m
> EDIT - 프리뷰 컴포넌트와 라우터 컴포넌트 flex align 조정

- .github/workflows/formatting.yml
- 이전에 cache path를 잘못 설정해줘서 매번 캐시 파일을 만드느라 오래걸렸던 ci를 개선했습니다.
- (이전에는 캐시를 안쓰는게 더 빨랐다는 사실!!... ㅠㅠ)
> 1m
> EDIT - github action 캐싱 전략 수정 및 ci 속도 개선

- src/hooks/user/useOrdersWebsocket.tsx
- 이전에 서버 엔드포인트를 변경하면서, 웹소켓 엔드포인트는 변경하지 않아서 생긴 오류를 수정했습니다.
> 1m
- 머지 후 바로 배포 pr 올리겠습니다.
> FIX - 웹소켓 엔드포인트 변경 안해서 생기는 오류 수정

- src/components/admin/order/OrderStickyNavBar.tsx
- src/components/user/order/OrderStatusBar.tsx
- src/hooks/useRefresh.tsx
- src/pages/user/order/OrderComplete.tsx
- 결제 확인 페이지에 새로운 디자인을 적용했습니다.
- 다만 현재 디자인 문서상에서 버튼의 기능은 좀 더 기획이 필요하다고 판단하여 구현하지 않았습니다.
- 계좌정보도 백엔드 및 프론트엔드 추가 구현이 필요한 부분이 있어서 현재 디자인과는 다르게 구현되어있습니다. (기능상으로는 같습니다.) 계좌 정보 등록 기능 부분을 개선하고 나서 이 부분을 수정할 예정입니다.
- 또한 이 페이지 한정으로 pull to refresh를 허용했습니다.
> 5m
주문 확인 화면
주문 취소 시 화면
> EDIT - 결제 확인 페이지 새로운 디자인 적용

- src/components/admin/order/OrderPayNavBar.tsx
- src/components/admin/order/OrderStickyNavBar.tsx
- src/components/user/order/OrderAccountInfo.tsx
- src/components/user/order/OrderButton.tsx
- src/components/user/order/OrderPayAccountInfo.tsx
- src/components/user/order/OrderPayDescription.tsx
- src/hooks/user/useWorkspace.tsx
- src/pages/user/order/Order.tsx
- src/pages/user/order/OrderComplete.tsx
- src/pages/user/order/OrderPay.tsx
- src/types/defaultValues.ts
- src/types/index.ts
- 더미로 구현되어 있던 부분들을 모두 구현했습니다.
- 주문 확인 페이지에서 토스 결제가 불가능 할 경우에 결제계좌만 가능하게끔 적용했습니다.
- 백엔드에 새로 적용된 account 타입 적용해서 계좌 정보를 보여주게끔 했습니다.
- 주문 버튼에 bold를 적용하고 텍스트를 수정했습니다.
- 주문 완료 화면에서 뒤로가기 버튼을 숨기고, 공유시 title을 삭제했습니다.
> 10m
> EDIT - 주문 확인 페이지 수정 및 새로운 account 타입 적용

- src/components/admin/order/ServedOrderCard.tsx
- src/components/admin/order/TableOrderCard.tsx
- src/components/admin/order/ToggleOrderCard.tsx
- src/components/admin/order/modal/OrderModalHeaderContents.tsx
- src/components/user/order/OrderTableHistoryCotent.tsx
- src/pages/user/order/OrderComplete.tsx
- src/types/defaultValues.ts
- src/types/index.ts
- order number 필드를 추가하고 적용했습니다. 이제 workspace 별로 주문 번호를 부여합니다.
- 라이브에서는 order number가 id 값을 가지도록 sql을 돌려줬는데 로컬에서는 해당 조치를 취하지 않아서 모두 0으로 보일 겁니다.
위에 2개가 redis 적용하고 난 모습입니다.
> 5m
> ADD - orderNumber 필드 추가 및 적용

- src/components/admin/order/ToggleOrderCard.tsx
- src/components/common/nav/TitleNavBar.tsx
- shouldForwardProp 옵션을 통해 기존에 발생한 경고 출력을 제거했습니다.
> 5m
> FIX - shouldForwardProp을 통한 스타일 prop 필터링

- src/pages/user/order/OrderComplete.tsx
- src/pages/user/order/OrderPay.tsx
- 고객이 주문을 완료한 다음에 다시 주문할 수 있는 버튼을 추가했습니다.
> 5m
- 주문 창을 닫거나, 새로운 주문을 했을 때, 이전 주문에 대한 상태를 확인 하고 싶을 때, 상단 바의 '공유' 아이콘을 통해서 클립보드에 링크를 복사했다면 해당 링크를 통해 확인할 수 있습니다.
- 해당 부분에 대해서 좀 더 정보를 명확히 제공해줘야할 것 같습니다.
> ADD - 다시 주문하기 버튼 추가

- src/components/common/input/AppInputWithLabel.tsx
- src/pages/user/Register.tsx
- 회원가입 페이지에 회원가입 가능한 이메일 도메인 링크 추가했습니다.
> 5m
> ADD - 회원가입 페이지에 회원가입 가능한 이메일 도메인 링크 추가하기

- src/components/admin/order/modal/OrderDetailModalButton.tsx
- 주문 모달창에서 esc 버튼으로 끌 수 있게 이벤트리스너 추가했습니다.
> 2m
> ADD - 주문 모달창에서 esc 버튼으로 끌 수 있게 이벤트리스너 추가

- src/components/admin/order/NotPaidOrderCard.tsx
- src/components/admin/order/PaidOrderCard.tsx
- src/components/admin/order/ServedOrderCard.tsx
- src/components/admin/order/modal/OrderDetailModal.tsx
- src/components/admin/order/modal/OrderDetailModalButton.tsx
- src/components/admin/order/modal/OrderModalFooterContents.tsx
- src/pages/admin/order/AdminOrderRealtime.tsx
https://github.com/user-attachments/assets/c52667a8-9684-4c4c-acdc-df0111695faa
https://github.com/user-attachments/assets/4f75e29f-dd47-4a69-945c-fc071e8a9f19
- 주문 상세 모달을 열고난 후, 주문 상태를 변화시키면 스크롤이 안되는 버그를 수정했습니다.
> 5m
```js
function useModal() {
const modalKey = 'modal-root';
const [isModalOpen, setModalOpen] = useState(false);
const openModal = () => {
setModalOpen(true);
// 모달창 open 시 배경 스크롤 금지 코드
document.body.style.overflow = 'hidden';
};
const closeModal = () => {
setModalOpen(false);
// 모달창 open 시 배경 스크롤 금지 해제 코드
document.body.style.overflow = 'auto';
};
return { isModalOpen, openModal, closeModal, modalKey };
}
```
- 위와 같이 모달이 열렸을 때, 배경 화면이 스크롤이 안되도록 하는 코드가 있습니다.
- `closeModal`을 호출해야지 배경 스크롤 금지가 해제됩니다.
- 주문 상태를 변화시키는 로직에서 `closeModal`을 호출하지 않았기에 스크롤이 계속 금지되어 발생한 문제였습니다.
```js …
```
> FIX - 주문 상세 모달을 열고 상태 변화 시, 스크롤이 안되는 버그 수정

- src/pages/user/home/HomeMobile.tsx
- 홈 화면이 모바일 뷰에서 깨지는 현상을 해결했습니다.
> 5m
- Graas, SignBoard, Ground 3개의 컴포넌트에 대해 bottom css 값의 단위를 %로 통일했습니다.
> FIX - 홈 화면 모바일 뷰 깨지는 현상 해결

- package.json
- src/App.tsx
- src/hooks/useNetwork.tsx
- src/hooks/useNetworkStatusNotifier.tsx
- yarn.lock
https://github.com/user-attachments/assets/829a7af1-d9ab-43a9-b3cc-301ea927599d
https://github.com/user-attachments/assets/5c0898a1-bc7f-4172-a61c-3deac3ce0535
- 사용자의 인터넷 연결 상태를 알아내고, 연결이 되어있지 않다면 '네트워크 연결이 끊어졌습니다.' 토스트 ui를 보여줍니다.
- 연결이 다시 된다면 '네트워크 연결이 복구되었습니다.' 토스트 ui를 보여줍니다.
> 5m
`navigator.onLine` 프로퍼티는 네트워크 인터페이스에 연결된 상태만 알려주며, 실제 인터넷 접근 가능 여부는 보장하지 않습니다. 따라서 다음과 같이 추가적인 검증 과정을 거칩니다.
1. **온라인 상태 확인**  
- `navigator.onLine === true`일 때만 `performCheck()` 호출  
2. **진짜 연결 테스트 (`performCheck`)**  
- Google의 작은 리소스(`google.com/favicon.ico`)에 `HEAD` 요청  
- 응답 성공 → `setIsOnline(true)`  
- 타임아웃/에러 → `setIsOnline(false)`  
> **참고**  
> - `window`의 [online](https://developer.mozilla.org/en-US/docs/Web/API/Window/online_event) 이벤트는 `navigator.onLine`이 `true`로 전환될 때 발생합니다.  
> - `offline` 이벤트는 …
> ADD - useNetwork 훅과 react-toastify 라이브러리를 통한 네트워크 연결 상태 알림 기능 구현

- .storybook/main.ts
- src/components/common/button/NewRoundedButton.tsx
- src/components/common/input/NewAppInput.stories.tsx
- src/components/common/input/NewAppInput.tsx
- src/components/user/order/OrderAccountInfo.tsx
https://github.com/user-attachments/assets/33c3768d-5789-4623-9325-afe03d58e81a
- NewAppInput 컴포넌트에 대해 Label, Link, RoundedAppButton 컴포넌트들을 prop으로 추가할 수 있게 했습니다.
- NewAppInput 컴포넌트 스토리북에 다양한 시나리오를 작성했습니다.
> 5m
```ts
interface NewAppInputProps extends React.InputHTMLAttributes<HTMLInputElement> {
enterHandler?: () => void;
width?: number;
height?: number;
label?: string;
buttonProps?: {
size?: CustomButtonSize;
buttonText: string;
};
linkProps?: {
linkText: string;
linkUrl: string;
};
}
```
- prop으로 다양한 요소들을 받을 수 있도록 변경했습니다.
> ADD - NewAppInput 컴포넌트 새로운 디자인 적용 및 스토리북 추가

- src/pages/user/order/OrderPay.tsx
- #242 해당 PR로 인해 사파리를 제외한 나머지 브라우저에서 토스 결제로 넘어가지지 않는 버그를 해결했습니다.
> 5m
```ts
const isSafari = userAgent.includes('safari') && !userAgent.includes('chrome');
```
- https://explore.whatismybrowser.com/useragents/explore/software_name/chrome/ 를 참고하여 필터링 변수를 선언했습니다.
- 크롬 및 엣지 브라우저만 navigator.Agent의 value에 `safari`와 `chrome`이 둘 다 등장하였습니다.
```ts
// Before
.catch(errorHandler)
if (isSafari && totalAmount !== 0) {
popup?.location.replace(tossUrl);
}
// After
.then(() => {
if (isSafari && totalAmount !== 0) {
popup?.location.replace(tossUrl);
}
});
```
- 비동기 과정에서 문제가 생겼을 때 토스로 redirection 하지 않도록 변경했습니다.
> FIX - 사파리를 제외한 나머지 브라우저에서 토스 결제로 넘어가지지 않는 버그 해결

- src/components/common/container/PreviewContainer.tsx
- src/pages/admin/AdminWorkspace.tsx
- src/pages/admin/order/AdminTableCount.tsx
- src/pages/user/order/Order.tsx
- 주문 미리보기 화면이 기존에는 container만 있던 구조에서 content까지 구현하게끔 수정했습니다.
- 주문 미리보기 문구에 onClick 이벤트를 달아 해당 화면의 링크로 넘어갈 수 있게끔 했습니다.
- 또한 주문 비리보기 화면에서 주문 시도시 주문이 불가능하다고 알려주는 alert를 추가했습니다.
> 5m
https://github.com/user-attachments/assets/30fed021-3441-4b41-8ee1-11d07524e639
> EDIT - 주문 미리보기 화면 리팩토링 및 미리보기 화면 주문시도시 alert 추가

- src/hooks/user/useOrdersWebsocket.tsx
- src/pages/admin/order/AdminOrderRealtime.tsx
- 실시간 주문 페이지 이탈 시 websocket unsubscribe 추가하여 중복적으로 subscribe하는 현상을 막았습니다.
- 기존에는 새로고침 없이 실시간 주문 조회 페이지를 여러번 들어가면 중복 구독이 되어 주문 소리가 겹치는 현상이 있었습니다.
- 또한 fetch도 구독된 횟수만큼 일어나서 서버에 대한 부담을 줄였습니다.
> 3m
Before: 소리 중첩 영상
https://github.com/user-attachments/assets/4ae37fca-3222-413e-8ff4-d22cc2458c9d
After: 해결된 영상
https://github.com/user-attachments/assets/d54a1ce8-2d2d-430d-8485-8891a28ac847
> ADD - 실시간 주문 페이지 이탈 시 websocket unsubscribe 추가

- src/components/admin/order/modal/OrderDetailModal.tsx
https://github.com/user-attachments/assets/8f0b19db-bf43-42f6-bf37-ea894256280e
https://github.com/user-attachments/assets/889a650b-c217-4650-84f8-6741355acfae
- 소켓 통신 상황에서 보고 있던 주문 모달 창이 예기치 않게 닫히는 경우, 모달을 열 때 설정한 `overflow: hidden` 속성이 그대로 남게 되어 스크롤이 막힙니다.
> 5m
```ts
function OrderDetailModal({ order, isModalOpen, closeModal }: Props) {
const { modalKey } = useModal();
// logic. . .
return () => {
document.body.style.overflow = 'auto';
};
}, []);
```
- OrderDetailModal 이 언마운트 될 때, `overflow: auto`로 설정하여 스크롤이 이루어지도록 합니다.
> FIX - 모달 스크롤 금지 버그 수정

- src/components/admin/order/table-manage/list/AdminTableOrderList.tsx
- src/components/admin/order/table-manage/setting/TableCount.tsx
- src/components/admin/order/table-manage/setting/TableTimeLimit.tsx
- src/components/admin/order/table-manage/timer/TableSessionControler.tsx
- src/components/admin/order/table-manage/timer/TableTimeButtons.tsx
- src/components/admin/order/table-manage/timer/TableTimeControler.tsx
- src/hooks/admin/useTableSession.tsx
- src/pages/admin/table/AdminOrderTable.tsx
- 테이블 관리 페이지에 대해 자잘한 수정을 진행했습니다.
- 기존에는 setTimeInterval로 5초 간격으로 데이터를 fetch해오고 있었습니다.(React Query로 빨리 바꿔야지,,)
- 새로고침 버튼을 통해 데이터를 refetch하는 로직을 추가했습니다.
- 들어온 주문의 상태들도 확인할 수 있도록 '주문상태' 필드를 추가했습니다.
- 세션이 시작되지 않은 테이블은 '상태변경' input에  주점 기본 세션 리밋이 보입니다.
- 세션이 시작되면 '상태변경' input에 10분을 기본으로 보여집니다.(해당 값은 세션 스토리지를 이용합니다.)
> 5m
- 기존 `TableSessionControler`의 로직들을 `useTableSession`라는 별도의 커스텀 훅으로 분리했습니다.
> EDIT - 테이블 관리 페이지 수정

- src/components/admin/order/table-manage/list/AdminTableOrderList.tsx
- src/components/admin/order/table-manage/qrcode/TableQRCode.tsx
- src/components/common/nav/NavBar.tsx
- src/components/common/nav/TitleNavBar.tsx
- src/pages/admin/table/AdminOrderTable.tsx
- 어드민 페이지에 주문하기 링크를 추가했습니다.
https://github.com/user-attachments/assets/373556b9-111a-48d8-a310-0721dcd7c5e6
- 기존 QR 다운로드 -> 주문하기 링크로 변경했습니다.
- NavBar 및 TitleNavBar에 min-width를 설정하여 화면을 작게 만들어도 레이아웃이 깨지지 않도록 했습니다.
https://github.com/user-attachments/assets/ea33bc11-4385-43b2-b64e-8b489af65eb8
> 5m
> EDIT - 어드민 페이지에 주문하기 링크 추가 및 기타 CSS 수정

- src/components/admin/order/table-manage/list/AdminTableOrderList.tsx
- src/components/admin/order/table-manage/list/TableListItem.tsx
- src/components/user/order/OrderFooter.tsx
- src/hooks/useServerHealth.tsx
- src/pages/admin/AdminHome.tsx
- src/pages/user/home/HomeMobile.tsx
- src/pages/user/home/HomePC.tsx
- 테이블 이동시 history 스택 쌓이지 않도록 수정
https://github.com/user-attachments/assets/4774aaa0-2f26-4f93-9b66-421cc7e45fa5
https://github.com/user-attachments/assets/1e700ddb-50a2-450d-888b-952cf13211db
- 주문 페이지 Footer의 padding top 추가
- 홈 화면, 메인 페이지에 FaQ 버튼 추가
https://github.com/user-attachments/assets/1169bea7-be15-43cf-aee0-64d90d1ab55c
- 테이블 별 주문 Fallback 스타일 조정
- health check URL 수정
> 5m
> EDIT - 자잘한 수정

- src/components/admin/order/table-manage/list/AdminTableOrderList.tsx
- src/components/admin/order/table-manage/list/OrderRowItem.tsx
- 실시간 테이블 관리 페이지에서 주문 상세 내역(모달) 정보 불일치 문제를 해결했습니다.
https://github.com/user-attachments/assets/542df6dc-d658-4750-bd64-5b06c9893e56
https://github.com/user-attachments/assets/061e1e56-15a6-46fe-b593-7701f5b8ef75
> 5m
- 해당 문제 원인은 React의 클로저 특성과 모달 상태 공유 때문입니다.
- tableOrders.map()내부에서 렌더링되는 각 OrderRowItem의 TableOrderDetailModal이 모두 **동일한 모달 상태(isModalOpen)**를 공유하고 있었습니다. 
- React의 렌더링 과정에서 map 함수가 실행될 때, 모든 모달 컴포넌트가 마지막으로 처리된 order 객체를 클로저로 참조하게 되어 어떤 "보기" 버튼을 클릭해도 항상 마지막 주문의 정보가 표시되는 문제가 발생했습니다.
```typescript
// 문제가 있던 코드 구조
{tableOrders.map((order) => (
<OrderRowItem key={order.id} order={order} />
// ↳ 내부에서 TableOrderDetailModal이 같은 모달 상태를 공유
))}
``` 
- 각 주문별로 독립적인 모달 상태를 관리하도록 OrderRowItem 컴포넌트 내부에서 개별 useModal 훅을 사용하는 방식으로 수정했습니다.
- 이를 통해 각 주문 행마다 고유한 모달 상태(isModalOpen, openModal, …
> FIX - 실시간 테이블 관리 페이지 주문 상세 내역 정보 불일치 문제 해결

- src/jotai/user/atoms.ts
- #329 해당 PR에서 추가한 로그 출력 결과를 확인해보니, 간헐적으로 `userWorkspaceAtom`의 값을 기본값으로 가져와는 버그가 발생했습니다.
- 이 부분이 스토리지의 값을 읽어와 atom을 초기화 하는 atomWithStorage와 연관이 있다 판단하여, userWorkspaceAtom의 속성을 기존atomWithStorage에서 atom으로 수정했습니다.
- 해당 조치를 취한 후에도 동일한 에러가 발생하는지 지속적인 모니터링이 필요하므로, 기존 로그 출력 코드 및 로직은 유지합니다.
> 5m
> EDIT - userWorkspaceAtom을 기존atomWithStorage에서 atom으로 수정

- src/resources/data/popupData.tsx
- src/utils/qrCode.ts
- 전체 QR 코드 다운로드하고 실제 출력시, QR코드 3 모퉁이에 있는 위치 지정 패턴이 잘릴 수 있는 위험이 있어, 이를 해결하고자 QR코드의 패딩을 추가했습니다.
- 인터뷰 팝업 만료일을 수정하여 더이상 뜨지 않도록 했습니다.
> 5m
> EDIT - 전체 QR 코드 다운로드 패딩 추가
